apiVersion: v2
name: photoprism
home: https://photoprism.org/
description: A Photoprism Helm chart for Kubernetes
appVersion: "260728"
version: 1.4.5
sources:
  - https://github.com/photoprism/photoprism
